"""Non-technical localhost control center for Jarvis data and status."""

from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter(tags=["control-center"])


CONTROL_PAGE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'self'">
<title>Jarvis Control Center</title><style>
:root{color-scheme:dark;font-family:Inter,'Segoe UI',sans-serif;background:#07111f;color:#edf7ff}
*{box-sizing:border-box}body{margin:0}.shell{max-width:1100px;margin:auto;padding:28px}.hero{display:flex;justify-content:space-between;gap:18px;align-items:center;margin-bottom:22px}
h1{font-size:36px;margin:0;color:#7ce7dc}.muted{color:#9cabc3}.badge{padding:8px 12px;border-radius:99px;background:#17344a;color:#7ce7dc}
nav{display:flex;gap:8px;flex-wrap:wrap;margin:20px 0}button,.button{border:0;border-radius:10px;padding:11px 15px;background:#273753;color:#edf7ff;font-weight:650;cursor:pointer}button.primary,nav button.active{background:#5eead4;color:#062f2c}button.danger{background:#5b2230;color:#fecdd3}
.panel{display:none}.panel.active{display:block}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:14px}.card{background:#101d31;border:1px solid #2a405e;border-radius:15px;padding:18px;margin-bottom:12px}.card h2,.card h3{margin-top:0}.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.row>*{flex:1}input,textarea,select{width:100%;padding:12px;border-radius:9px;border:1px solid #385172;background:#081321;color:#fff;margin:5px 0 10px}textarea{min-height:90px;resize:vertical}.status{font-size:18px}.ok{color:#72e6a6}.warn{color:#ffce78}.chat{height:340px;overflow:auto;white-space:pre-wrap}.message{padding:12px;border-radius:12px;margin:8px 0;background:#172640}.message.jarvis{background:#12342f}.small{font-size:13px}.empty{padding:24px;color:#9cabc3;text-align:center}.toast{position:fixed;right:22px;bottom:22px;background:#172640;padding:14px 18px;border-radius:10px;display:none}
</style></head><body><div class="shell"><div class="hero"><div><h1>Jarvis Control Center</h1><div class="muted">Private, local, and under your control.</div></div><div id="ready" class="badge">Checking...</div></div>
<nav><button class="active" data-tab="home">Home</button><button data-tab="talk">Talk</button><button data-tab="memory">Memory</button><button data-tab="projects">Projects</button><button data-tab="reminders">Reminders</button></nav>
<section id="home" class="panel active"><div class="grid"><div class="card"><h3>Background voice</h3><div id="voice" class="status">Checking...</div><p class="muted small">Say “Hey Jarvis” anywhere. You can interrupt while it speaks.</p></div><div class="card"><h3>Room monitoring</h3><div id="presence" class="status">Checking...</div><p class="muted small">The camera stays fully off until monitoring is enabled.</p><button id="presenceToggle" onclick="togglePresence()" disabled>Checking...</button></div><div class="card"><h3>Identity</h3><div id="identity" class="status">Checking...</div></div><div class="card"><h3>Privacy</h3><div class="status ok">Local by default</div><p class="muted small">Audio and snapshots are transient. Memory stays in SQLite on this laptop.</p></div></div></section>
<section id="talk" class="panel"><div class="card"><h2>Conversation</h2><div id="chat" class="chat"><div class="empty">Type here when voice is inconvenient.</div></div><form id="chatForm"><div class="row"><input id="chatInput" maxlength="4000" placeholder="Ask Jarvis anything..." required><button class="primary" type="submit">Send</button></div></form></div></section>
<section id="memory" class="panel"><div class="card"><h2>Add memory</h2><form id="memoryForm"><div class="row"><input id="memoryCategory" placeholder="Category, e.g. preference" required><input id="memoryKey" placeholder="Name, e.g. editor" required></div><textarea id="memoryValue" placeholder="What Jarvis should remember" required></textarea><button class="primary">Remember</button></form></div><div id="memoryList"></div></section>
<section id="projects" class="panel"><div class="card"><h2>New project</h2><form id="projectForm"><input id="projectName" placeholder="Project name" required><textarea id="projectObjective" placeholder="Objective" required></textarea><input id="projectDeadline" type="date"><button class="primary">Create project</button></form></div><div id="projectList"></div></section>
<section id="reminders" class="panel"><div class="card"><h2>New reminder</h2><form id="reminderForm"><input id="reminderTitle" placeholder="What should Jarvis remind you about?" required><input id="reminderTime" type="datetime-local" required><button class="primary">Schedule</button></form></div><div id="reminderList"></div></section>
</div><div id="toast" class="toast"></div><script>
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options={}){const response=await fetch(path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});if(!response.ok){let detail='Request failed';try{detail=(await response.json()).detail||detail}catch{}throw new Error(detail)}if(response.status===204)return null;return response.json()}
function toast(text){const box=$('#toast');box.textContent=text;box.style.display='block';setTimeout(()=>box.style.display='none',2600)}
document.querySelectorAll('nav button').forEach(button=>button.onclick=()=>{document.querySelectorAll('nav button,.panel').forEach(x=>x.classList.remove('active'));button.classList.add('active');$(`#${button.dataset.tab}`).classList.add('active');load(button.dataset.tab)});
async function loadStatus(){try{const [health,voice,identity,presence]=await Promise.all([api('/health'),api('/voice/runtime-status'),api('/identity/status'),api('/presence/status')]);$('#ready').textContent=health.status==='ok'?'Jarvis ready':'Needs attention';$('#voice').className=`status ${voice.running&&voice.enabled?'ok':'warn'}`;$('#voice').textContent=voice.running&&voice.enabled?`Listening · ${voice.state}`:(voice.last_error||'Paused');$('#identity').textContent=identity.enrolled_profiles?.length?(identity.session_authorized?'Authorized':'Face enrolled'):'Not enrolled';$('#presence').className=`status ${presence.enabled?'ok':''}`;$('#presence').textContent=presence.enabled?'On · camera on':'Off · camera off';const button=$('#presenceToggle');button.disabled=false;button.dataset.enabled=String(presence.enabled);button.textContent=presence.enabled?'Turn monitoring off':'Turn monitoring on';}catch(error){$('#ready').textContent='Jarvis offline';$('#voice').textContent=error.message}}
async function togglePresence(){const button=$('#presenceToggle');button.disabled=true;try{await api(button.dataset.enabled==='true'?'/presence/disable':'/presence/enable',{method:'POST'});await loadStatus();toast('Room monitoring updated')}catch(error){toast(error.message);button.disabled=false}}
async function loadMemory(){const items=await api('/memory');$('#memoryList').innerHTML=items.length?items.map(item=>`<div class="card" data-memory="${item.id}" data-category="${esc(item.category)}" data-key="${esc(item.key)}"><div class="row"><strong>${esc(item.category)} · ${esc(item.key)}</strong><button class="danger" onclick="forgetMemory(${item.id})">Delete</button></div><textarea id="mv${item.id}">${esc(item.value)}</textarea><button onclick="saveMemory(${item.id})">Save changes</button></div>`).join(''):'<div class="empty">No saved memory yet.</div>'}
async function saveMemory(id){const card=document.querySelector(`[data-memory="${id}"]`);await api('/memory',{method:'PUT',body:JSON.stringify({category:card.dataset.category,key:card.dataset.key,value:$(`#mv${id}`).value})});toast('Memory updated');loadMemory()}
async function forgetMemory(id){if(!confirm('Delete this memory?'))return;await api(`/memory/${id}`,{method:'DELETE'});toast('Memory deleted');loadMemory()}
$('#memoryForm').onsubmit=async event=>{event.preventDefault();await api('/memory',{method:'PUT',body:JSON.stringify({category:$('#memoryCategory').value,key:$('#memoryKey').value,value:$('#memoryValue').value})});event.target.reset();toast('Remembered locally');loadMemory()};
async function loadProjects(){const projects=await api('/projects');const cards=[];for(const project of projects){const tasks=await api(`/projects/${project.id}/tasks`);cards.push(`<div class="card"><h3>${esc(project.name)}</h3><p>${esc(project.objective)}</p><div class="muted small">${esc(project.status)}${project.deadline?' · '+esc(project.deadline):''}</div><div>${tasks.map(task=>`<label><input type="checkbox" ${task.status==='completed'?'checked':''} onchange="taskStatus(${task.id},this.checked)"> ${esc(task.title)}</label>`).join('<br>')||'<p class="muted">No tasks yet.</p>'}</div><form onsubmit="addTask(event,${project.id})"><div class="row"><input name="title" placeholder="Next action" required><button>Add task</button></div></form></div>`)}$('#projectList').innerHTML=cards.join('')||'<div class="empty">No projects yet.</div>'}
$('#projectForm').onsubmit=async event=>{event.preventDefault();await api('/projects',{method:'POST',body:JSON.stringify({name:$('#projectName').value,objective:$('#projectObjective').value,deadline:$('#projectDeadline').value||null})});event.target.reset();toast('Project created');loadProjects()};
async function addTask(event,id){event.preventDefault();await api(`/projects/${id}/tasks`,{method:'POST',body:JSON.stringify({title:event.target.title.value})});loadProjects()}
async function taskStatus(id,done){await api(`/project-tasks/${id}`,{method:'PATCH',body:JSON.stringify({status:done?'completed':'pending'})});toast('Task updated')}
async function loadReminders(){const items=await api('/reminders?include_delivered=true');$('#reminderList').innerHTML=items.length?items.map(item=>`<div class="card"><strong>${esc(item.title)}</strong><div class="muted">${new Date(item.due_at).toLocaleString()} · ${esc(item.status)}</div></div>`).join(''):'<div class="empty">No reminders yet.</div>'}
$('#reminderForm').onsubmit=async event=>{event.preventDefault();const due=new Date($('#reminderTime').value);await api('/reminders',{method:'POST',body:JSON.stringify({title:$('#reminderTitle').value,due_at:due.toISOString()})});event.target.reset();toast('Reminder scheduled');loadReminders()};
$('#chatForm').onsubmit=async event=>{event.preventDefault();const text=$('#chatInput').value.trim();if(!text)return;const chat=$('#chat');if(chat.querySelector('.empty'))chat.innerHTML='';chat.innerHTML+=`<div class="message">You: ${esc(text)}</div>`;$('#chatInput').value='';try{const answer=await api('/assistant/respond',{method:'POST',body:JSON.stringify({text})});chat.innerHTML+=`<div class="message jarvis">Jarvis: ${esc(answer.reply)}</div>`}catch(error){chat.innerHTML+=`<div class="message">${esc(error.message)}</div>`}chat.scrollTop=chat.scrollHeight};
function load(tab){if(tab==='memory')loadMemory();if(tab==='projects')loadProjects();if(tab==='reminders')loadReminders();if(tab==='home')loadStatus()}
loadStatus();setInterval(loadStatus,5000);
</script></body></html>"""


@router.get("/control", response_class=HTMLResponse)
async def control_center() -> HTMLResponse:
    """Return the local, non-technical management interface."""
    return HTMLResponse(CONTROL_PAGE)
